### ISSUE TITLE
Some trouble during transfer .txt to .mallet fomat

### ISSUE THREAD

**Issue by SCAUapc** [ethanhezhao/MetaLDA#1]
Hello, my name is Apc. I follow your step in Readme, but when i enter this in cmd:

<mallet_location>/bin/mallet import-file --input train_doc.txt --output train_doc.mallet --label-as-features --keep-sequence --line-regex '([^\t]+)\t([^\t]+)\t(.*)'  

It always said that Exception in thread "main" java .lang.IllegalStateException : Line #1 does not match regex.
The dataset i try is in this project data/WS/train_doc.txt, but it doesn't work. Have you meet this problem?

**Comment by ethanhezhao** [comment]
Hi Apc, I just downloaded the code and tried "demo.sh" and it works for me. I would suggest checking your Mallet installation and whether WS/train_doc.txt has been modified. You may also want to download the repo again and try demo.sh.

**Comment by SCAUapc** [comment]
> Hi Apc, I just downloaded the code and tried "demo.sh" and it works for me. I would suggest checking your Mallet installation and whether WS/train_doc.txt has been modified. You may also want to download the repo again and try demo.sh.

Thanks! ！I try to run demo.sh, and meet some trouble, but now i can run it successfully.I think it maybe beacuse i have opened  WS/train_doc.txt with default notebook program comes from my PC, but not notepad++.
